name: Python Test
on: 
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies 
      run: pip install -r requirments.txt

    - name: Run tests 
      run: python -m pytest

    - name: Upload Test Results Artifact # So if any other action depends on it can work
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results/

